### ISSUE TITLE
Pictures can not be displayed normally after importing data

### ISSUE THREAD

**Issue by yihanglee-cn** [lincolnthalles/memospot#11]
### Describe the bug

Hi, lincolnthalles, Sorry to bother you.
I have a memos Docker container running on a cloud server，download docker container's data and copy it to memospot default folder，but pictures can't be displayed normally.
I choose 'Local file system' on my Docker container and the version is also 0.18.1

### Steps to reproduce

1. Download data(.memos) from Docker container
2. Copy .db, .db-shm, .db-wal, asserts folder to memospot default folder(%AppData%\memospot)
3. Open memospot and login
4. Text data is normal, but pictures can not be displayed normally

### Screenshots or additional context

![image](https://github.com/lincolnthalles/memospot/assets/31716253/9b273b6f-e8b3-45dd-98d1-4f305527880a)

**Comment by lincolnthalles** [comment]
No problem.

As you chose to store files on disk, absolute paths to resources are hardcoded in the database. In this case, you must update them manually when moving between systems/folder structures.

I didn't manage to publish the docs yet, but you can check [MIGRATION.md](https://github.com/lincolnthalles/memospot/blob/main/docs/topics/MIGRATION.md). Pretty much all of this is covered.

**Comment by yihanglee-cn** [comment]
Thanks for you help, i've resolved zhis issue
Pictures are  now dispalying normally
🫡🫡🫡

**Comment by yihanglee-cn** [comment]
But, i have a new question😂
When I use memospot to insert a new picture, the internal_path recorded in the data table is an absolute path.
Like this:
![image](https://github.com/lincolnthalles/memospot/assets/31716253/95be4b97-217c-4185-99f1-f0b5c65f73ff)
If I use webdav to synchronize the data directory to other computers, the images may not be displayed properly because the image paths are incorrect.
Is there a way to use relative paths for newly inserted images?

**Comment by lincolnthalles** [comment]
Currently, no. That would require patching Memos server itself to store relative paths.

I plan to allow data folder to be moved, so you can put it inside OneDrive or other cloud provider, but it still would require all synced machines to use the same directory structure.

The 100% portable way is to use the database object storage, which should work fine until you start storing videos. The downside is that this approach will increase data transfers during syncs.

**Comment by yihanglee-cn** [comment]
👌Okay, get it, thanks a million
