### ISSUE TITLE
how to connect private server

### ISSUE THREAD

**Issue by liuxing7954** [lincolnthalles/memospot#34]
### Is your feature request related to a problem?

how to connect private server

### Describe the solution you'd like

how to connect private server

**Comment by lincolnthalles** [comment]
Do you mean connecting to another hosted Memos instance? That's currently not supported.
I may consider adding that feature in a future version, but it's not a priority.

You can use [Ferdium](https://ferdium.org) as a client for hosted instances. It already has a Memos recipe, you just need to add the server URL.

**Comment by liuxing7954** [comment]
> Do you mean connecting to another hosted Memos instance? That's currently not supported. I may consider adding that feature in a future version, but it's not a priority.
> 
> You can use [Ferdium](https://ferdium.org) as a client for hosted instances. It already has a Memos recipe, you just need to add the server URL.

thank you so much
