### ISSUE TITLE
on Windows 10 it doesnt go further than intro menu

### ISSUE THREAD

**Issue by diomed** [lincolnthalles/memospot#4]
### Describe the bug

![memospot](https://github.com/lincolnthalles/memospot/assets/72777/f0337e59-5ee5-43cc-959d-3497f72da0dd)

and restarting does not help

### Steps to reproduce

just open app on win 10

**Comment by lincolnthalles** [comment]
Have you installed the msi package?

I think I already figured out the issue. The msi package installs it to the Program Files folder, and the server tries to create the database there, where there is no permission.

The nsis .exe package should work fine, as it installs to AppData.

For now, I will remove the msi package and address this on the next release.

**Comment by diomed** [comment]
yes, this was due to .msi installation and yes. exe works fine. 

thanks for help.
